### ISSUE TITLE
Rosmake lsd_slam_viewer [FAIL]

### ISSUE THREAD

**Issue by Luedeke** [tum-vision/lsd_slam#300]
Hallo,
I'm still new to this topic, so I think I'm making a beginner's mistake here but google didn't help me.
I use Ubuntu 14.04.5 and ROS Indigo. Thanks for your time and help.
I followed the tutorial in the README, unfortunately there is the following error:

rosmake lsd_slam
[ rosmake ] rosmake starting...                                                 
[ rosmake ] Packages requested are: ['lsd_slam']                                
[ rosmake ] Logging to directory /home/ros-ubuntu-1404-5/.ros/rosmake/rosmake_output-20180401-174252
[ rosmake ] Expanded args ['lsd_slam'] to:
['lsd_slam_core', 'lsd_slam_viewer'] 
[rosmake-0] Starting >>> catkin [ make ]                                        
[rosmake-0] Finished <<< catkin ROS_NOBUILD in package catkin
 No Makefile in package catkin
[rosmake-0] Starting >>> genmsg [ make ]                                        
[rosmake-0] Finished <<< genmsg ROS_NOBUILD in package genmsg
 No Makefile in package genmsg
[rosmake-0] Starting >>> genlisp [ make ]                                       
[rosmake-1] Starting >>> genpy [ make ]                                         
[rosmake-0] Finished <<< genlisp ROS_NOBUILD in package genlisp
 No Makefile in package genlisp
[rosmake-0] Starting >>> gencpp [ make ]                                        
[rosmake-1] Finished <<< genpy ROS_NOBUILD in package genpy
 No Makefile in package genpy
[rosmake-1] Starting >>> cpp_common [ make ]                                    
[rosmake-0] Finished <<< gencpp ROS_NOBUILD in package gencpp
 No Makefile in package gencpp
[rosmake-1] Finished <<< cpp_common ROS_NOBUILD in package cpp_common
 No Makefile in package cpp_common
[rosmake-0] Starting >>> message_generation [ make ]                            
[rosmake-1] Starting >>> rostime [ make ]                                       
[rosmake-1] Finished <<< rostime ROS_NOBUILD in package rostime
 No Makefile in package rostime
[rosmake-1] Starting >>> roscpp_traits [ make ]                                 
[rosmake-0] Finished <<< message_generation ROS_NOBUILD in package message_generation
 No Makefile in package message_generation
[rosmake-0] Starting >>> cmake_modules [ make ]                                 
[rosmake-1] Finished <<< roscpp_traits ROS_NOBUILD in package roscpp_traits
 No Makefile in package roscpp_traits
[rosmake-1] Starting >>> roscpp_serialization [ make ]                          
[rosmake-0] Finished <<< cmake_modules ROS_NOBUILD in package cmake_modules
 No Makefile in package cmake_modules
[rosmake-1] Finished <<< roscpp_serialization ROS_NOBUILD in package roscpp_serialization
 No Makefile in package roscpp_serialization
[rosmake-1] Starting >>> message_runtime [ make ]                               
[rosmake-0] Starting >>> rospack [ make ]                                       
[rosmake-1] Finished <<< message_runtime ROS_NOBUILD in package message_runtime
 No Makefile in package message_runtime
[rosmake-1] Starting >>> std_msgs [ make ]                                      
[rosmake-1] Finished <<< std_msgs ROS_NOBUILD in package std_msgs
 No Makefile in package std_msgs
[rosmake-1] Starting >>> geometry_msgs [ make ]                                 
[rosmake-1] Finished <<< geometry_msgs ROS_NOBUILD in package geometry_msgs
 No Makefile in package geometry_msgs
[rosmake-1] Starting >>> sensor_msgs [ make ]                                   
[rosmake-1] Finished <<< sensor_msgs ROS_NOBUILD in package sensor_msgs
 No Makefile in package sensor_msgs
[rosmake-1] Starting >>> rosbuild [ make ]                                      
[rosmake-1] Finished <<< rosbuild ROS_NOBUILD in package rosbuild
 No Makefile in package rosbuild
[rosmake-1] Starting >>> rosgraph_msgs [ make ]                                 
[rosmake-1] Finished <<< rosgraph_msgs ROS_NOBUILD in package rosgraph_msgs
 No Makefile in package rosgraph_msgs
[rosmake-1] Starting >>> rosgraph [ make ]                                      
[rosmake-1] Finished <<< rosgraph ROS_NOBUILD in package rosgraph
 No Makefile in package rosgraph
[rosmake-1] Starting >>> rosparam [ make ]                                      
[rosmake-1] Finished <<< rosparam ROS_NOBUILD in package rosparam
 No Makefile in package rosparam
[rosmake-1] Starting >>> rosmaster [ make ]                                     
[rosmake-1] Finished <<< rosmaster ROS_NOBUILD in package rosmaster
 No Makefile in package rosmaster
[rosmake-1] Starting >>> roslang [ make ]                                       
[rosmake-1] Finished <<< roslang ROS_NOBUILD in package roslang
 No Makefile in package roslang
[rosmake-1] Starting >>> xmlrpcpp [ make ]                                      
[rosmake-1] Finished <<< xmlrpcpp ROS_NOBUILD in package xmlrpcpp
 No Makefile in package xmlrpcpp
[rosmake-1] Starting >>> rosclean [ make ]                                      
[rosmake-1] Finished <<< rosclean ROS_NOBUILD in package rosclean
 No Makefile in package rosclean
[rosmake-0] Finished <<< rospack ROS_NOBUILD in package rospack
 No Makefile in package rospack
[rosmake-0] Starting >>> roslib [ make ]                                        
[rosmake-0] Finished <<< roslib ROS_NOBUILD in package roslib
 No Makefile in package roslib
[rosmake-0] Starting >>> rosunit [ make ]                                       
[rosmake-0] Finished <<< rosunit ROS_NOBUILD in package rosunit
 No Makefile in package rosunit
[rosmake-0] Starting >>> rosconsole [ make ]                                    
[rosmake-0] Finished <<< rosconsole ROS_NOBUILD in package rosconsole
 No Makefile in package rosconsole
[rosmake-0] Starting >>> roscpp [ make ]                                        
[rosmake-0] Finished <<< roscpp ROS_NOBUILD in package roscpp
 No Makefile in package roscpp
[rosmake-1] Starting >>> roslz4 [ make ]                                        
[rosmake-0] Starting >>> rosout [ make ]                                        
[rosmake-0] Finished <<< rosout ROS_NOBUILD in package rosoutve 28/42 Complete ]
 No Makefile in package rosout
[rosmake-0] Starting >>> roslaunch [ make ]                                     
[rosmake-0] Finished <<< roslaunch ROS_NOBUILD in package roslaunch
 No Makefile in package roslaunch
[rosmake-1] Finished <<< roslz4 ROS_NOBUILD in package roslz4
 No Makefile in package roslz4
[rosmake-0] Starting >>> rospy [ make ]                                         
[rosmake-1] Starting >>> rosbag_storage [ make ]                                
[rosmake-0] Finished <<< rospy ROS_NOBUILD in package rospy
 No Makefile in package rospy
[rosmake-0] Starting >>> rostest [ make ]                                       
[rosmake-0] Finished <<< rostest ROS_NOBUILD in package rostest
 No Makefile in package rostest
[rosmake-0] Starting >>> cv_bridge [ make ]                                     
[rosmake-1] Finished <<< rosbag_storage ROS_NOBUILD in package rosbag_storage
 No Makefile in package rosbag_storage
[rosmake-1] Starting >>> topic_tools [ make ]                                   
[rosmake-0] Finished <<< cv_bridge ROS_NOBUILD in package cv_bridge
 No Makefile in package cv_bridge
[rosmake-1] Finished <<< topic_tools ROS_NOBUILD in package topic_tools
 No Makefile in package topic_tools
[rosmake-1] Starting >>> rosbag [ make ]                                        
[rosmake-1] Finished <<< rosbag ROS_NOBUILD in package rosbag
 No Makefile in package rosbag
[rosmake-1] Starting >>> rosmsg [ make ]                                        
[rosmake-1] Finished <<< rosmsg ROS_NOBUILD in package rosmsg
 No Makefile in package rosmsg
[rosmake-1] Starting >>> rosservice [ make ]                                    
[rosmake-1] Finished <<< rosservice ROS_NOBUILD in package rosservice
 No Makefile in package rosservice
[rosmake-1] Starting >>> dynamic_reconfigure [ make ]                           
[rosmake-1] Finished <<< dynamic_reconfigure ROS_NOBUILD in package dynamic_reconfigure
 No Makefile in package dynamic_reconfigure
[rosmake-0] Starting >>> lsd_slam_viewer [ make ]                               
[ rosmake ] Last 40 linesd_slam_viewer: 9.8 sec ]    [ 1 Active 40/42 Complete ]
{-------------------------------------------------------------------------------
  -- Looking for Q_WS_MAC
  -- Looking for Q_WS_MAC - not found
  -- Found Qt4: /usr/bin/qmake (found version "4.8.6") 
  -- Found QGLVIEWER: /usr/include/QGLViewer  
  MSG: gencfg_cpp on:LSDSLAMViewerParams.cfg
  ERROR [gendeps] 1 Finding dependencies for /home/ros-ubuntu-1404-5/rosbuild_ws/package_dir/lsd_slam/lsd_slam_viewer/cfg/LSDSLAMViewerParams.cfg
  ***********************************************************************************
  load_module did not return. Unable to determine dependencies for file listed above.
  ***********************************************************************************
  Traceback (most recent call last):
    File "/opt/ros/indigo/share/dynamic_reconfigure/cmake/gendeps", line 66, in <module>
      imp.load_module("__main__", f, srcfile, ('.cfg', 'U', 1))
    File "/home/ros-ubuntu-1404-5/rosbuild_ws/package_dir/lsd_slam/lsd_slam_viewer/cfg/LSDSLAMViewerParams.cfg", line 20, in <module>
      gen.add("scaledDepthVarTH", double_t, 0, "log10 of threshold on point's variance, in the respective keyframe's scale. ", -3, -10, 1)
    File "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py", line 273, in add
      self.group.add(name, paramtype, level, description, default, min, max, edit_method) 
    File "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py", line 143, in add
      check_description(description)
    File "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py", line 68, in check_description
      raise Exception(r"""quotes not allowed in description string `%s`""" % description)
  Exception: quotes not allowed in description string `log10 of threshold on point's variance, in the respective keyframe's scale. `
  
  CMake Error at /opt/ros/indigo/share/dynamic_reconfigure/cmake/cfgbuild.cmake:78 (string):
    string sub-command REPLACE requires at least four arguments.
  Call Stack (most recent call first):
    /opt/ros/indigo/share/dynamic_reconfigure/cmake/cfgbuild.cmake:99 (gencfg_cpp)
    CMakeLists.txt:29 (include)
  
  
  -- Performing Test HAS_SSE3_EXTENSIONS
  -- Performing Test HAS_SSE3_EXTENSIONS - Success
  -- Performing Test HAS_SSE2_EXTENSIONS
  -- Performing Test HAS_SSE2_EXTENSIONS - Success
  -- Performing Test HAS_SSE_EXTENSIONS
  -- Performing Test HAS_SSE_EXTENSIONS - Success
  -- [rosbuild] Found SSE3 extensions, using flags: -msse3 -mfpmath=sse
  -- Configuring incomplete, errors occurred!
  See also "/home/ros-ubuntu-1404-5/rosbuild_ws/package_dir/lsd_slam/lsd_slam_viewer/build/CMakeFiles/CMakeOutput.log".
  See also "/home/ros-ubuntu-1404-5/rosbuild_ws/package_dir/lsd_slam/lsd_slam_viewer/build/CMakeFiles/CMakeError.log".
-------------------------------------------------------------------------------}
[ rosmake ] Output from build of package lsd_slam_viewer written to:
[ rosmake ]    /home/ros-ubuntu-1404-5/.ros/rosmake/rosmake_output-20180401-174252/lsd_slam_viewer/build_output.log
[rosmake-0] Finished <<< lsd_slam_viewer [FAIL] [ 9.82 seconds ]                
[ rosmake ] Halting due to failure in package lsd_slam_viewer. 
[ rosmake ] Waiting for other threads to complete.
[ rosmake ] Results:                                                            
[ rosmake ] Built 41 packages with 1 failures.                                  
[ rosmake ] Summary output to directory                                         
[ rosmake ] /home/ros-ubuntu-1404-5/.ros/rosmake/rosmake_output-20180401-174252

**Comment by SowmyaN9** [comment]
@Luedeke  : I faced the same issue ;) Look at the line : 
> raise Exception(r"""quotes not allowed in description string %s""" % description)
> Exception: quotes not allowed in description string log10 of threshold on point's variance, in the respective keyframe's scale.
Its a python related error, either remove ' (in keyframe 's) in the string mentioned above found in the file LSDSLAMViewerParams.cfg, line 20 or add  r before start of the string in line 20.
Hope this helps!!
