### ISSUE TITLE
rosmake lsd_slam failure

### ISSUE THREAD

**Issue by jacksonkr** [tum-vision/lsd_slam#316]
Ubuntu 14.04
ROS Indigo
LSD Slam - master

`$ rosmake lsd_slam`

```
...
  -- [rosbuild] Found SSE3 extensions, using flags: -msse3 -mfpmath=sse
  -- Configuring incomplete, errors occurred!
  See also "/home/jackson/rosbuild_ws/package_dir/lsd_slam/lsd_slam_viewer/build/CMakeFiles/CMakeOutput.log".
  See also "/home/jackson/rosbuild_ws/package_dir/lsd_slam/lsd_slam_viewer/build/CMakeFiles/CMakeError.log".
-------------------------------------------------------------------------------}
[ rosmake ] Output from build of package lsd_slam_viewer written to:
[ rosmake ]    /home/jackson/.ros/rosmake/rosmake_output-20180721-211940/lsd_slam_viewer/build_output.log
[rosmake-0] Finished <<< lsd_slam_viewer [FAIL] [ 2.87 seconds ]                
[ rosmake ] Halting due to failure in package lsd_slam_viewer. 
[ rosmake ] Waiting for other threads to complete.
[ rosmake ] Results:                                                            
[ rosmake ] Built 41 packages with 1 failures.                                  
[ rosmake ] Summary output to directory                                         
[ rosmake ] /home/jackson/.ros/rosmake/rosmake_output-20180721-211940   
```
**rosmake_output-20180721-211940**

```
Build failures with context:
---------------------
lsd_slam_viewer
mkdir -p bin
cd build && cmake -Wdev -DCMAKE_TOOLCHAIN_FILE=/opt/ros/indigo/share/ros/core/rosbuild/rostoolchain.cmake  ..
[rosbuild] Building package lsd_slam_viewer
[rosbuild] using multiarch 'x86_64-linux-gnu' for finding Boost
-- Using CATKIN_DEVEL_PREFIX: /home/jackson/rosbuild_ws/package_dir/lsd_slam/lsd_slam_viewer/build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Skip enable_testing() for dry packages
-- Using CATKIN_TEST_RESULTS_DIR: /home/jackson/rosbuild_ws/package_dir/lsd_slam/lsd_slam_viewer/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.19
-- Using these message generators: gencpp;genlisp;genpy
[rosbuild] Including /opt/ros/indigo/share/roslisp/rosbuild/roslisp.cmake
[rosbuild] Including /opt/ros/indigo/share/roscpp/rosbuild/roscpp.cmake
[rosbuild] Including /opt/ros/indigo/share/rospy/rosbuild/rospy.cmake
MSG: gencfg_cpp on:LSDSLAMViewerParams.cfg
ERROR [gendeps] 1 Finding dependencies for /home/jackson/rosbuild_ws/package_dir/lsd_slam/lsd_slam_viewer/cfg/LSDSLAMViewerParams.cfg
***********************************************************************************
load_module did not return. Unable to determine dependencies for file listed above.
***********************************************************************************
Traceback (most recent call last):
  File "/opt/ros/indigo/share/dynamic_reconfigure/cmake/gendeps", line 66, in <module>
    imp.load_module("__main__", f, srcfile, ('.cfg', 'U', 1))
  File "/home/jackson/rosbuild_ws/package_dir/lsd_slam/lsd_slam_viewer/cfg/LSDSLAMViewerParams.cfg", line 20, in <module>
    gen.add("scaledDepthVarTH", double_t, 0, "log10 of threshold on point's variance, in the respective keyframe's scale. ", -3, -10, 1)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py", line 274, in add
    self.group.add(name, paramtype, level, description, default, min, max, edit_method)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py", line 145, in add
    check_description(description)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py", line 69, in check_description
    raise Exception(r"""quotes not allowed in description string `%s`""" % description)
Exception: quotes not allowed in description string `log10 of threshold on point's variance, in the respective keyframe's scale. `

CMake Error at /opt/ros/indigo/share/dynamic_reconfigure/cmake/cfgbuild.cmake:78 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  /opt/ros/indigo/share/dynamic_reconfigure/cmake/cfgbuild.cmake:99 (gencfg_cpp)
  CMakeLists.txt:29 (include)


-- [rosbuild] Found SSE3 extensions, using flags: -msse3 -mfpmath=sse
-- Configuring incomplete, errors occurred!
See also "/home/jackson/rosbuild_ws/package_dir/lsd_slam/lsd_slam_viewer/build/CMakeFiles/CMakeOutput.log".
See also "/home/jackson/rosbuild_ws/package_dir/lsd_slam/lsd_slam_viewer/build/CMakeFiles/CMakeError.log".
make: *** [all] Error 1
```

What's going on here? Is there an easy way to get around this?

**Comment by jacksonkr** [comment]
Duplicate of #300
