### ISSUE TITLE
ERROR [gendeps] 1 Finding dependencies for /home/username/rosbuild_ws/package_dir/lsd_slam/lsd_slam_viewer/cfg/LSDSLAMViewerParams.cfg

### ISSUE THREAD

**Issue by swiss-knight** [tum-vision/lsd_slam#330]
I am having this error message while running `rosmake lsd_slam` fro the `~/rosbuild_ws/package_dir` directory where I cloned the lsd_slam github repository :

```
$ rosmake lsd_slam
[ rosmake ] rosmake starting...                                                                                                                                
[ rosmake ] Packages requested are: ['lsd_slam']                                                                                                               
[ rosmake ] Logging to directory /home/username/.ros/rosmake/rosmake_output-20190218-162754                                                                     
[ rosmake ] Expanded args ['lsd_slam'] to:
['lsd_slam_core', 'lsd_slam_viewer']                                                                                
[rosmake-0] Starting >>> catkin [ make ]                                                                                                                       
[rosmake-0] Finished <<< catkin ROS_NOBUILD in package catkin
 No Makefile in package catkin                                                                   
[rosmake-0] Starting >>> genmsg [ make ]                                                                                                                       
[rosmake-0] Finished <<< genmsg ROS_NOBUILD in package genmsg
 No Makefile in package genmsg                                                                   
[rosmake-0] Starting >>> genpy [ make ]                                                                                                                        
[rosmake-2] Starting >>> cpp_common [ make ]                                                                                                                   
[rosmake-1] Starting >>> genlisp [ make ]                                                                                                                      
[rosmake-3] Starting >>> gencpp [ make ]                                                                                                                       
[rosmake-0] Finished <<< genpy ROS_NOBUILD in package genpy
 No Makefile in package genpy                                                                      
[rosmake-0] Starting >>> geneus [ make ]                                                                                                                       
[rosmake-1] Finished <<< genlisp ROS_NOBUILD in package genlisp
 No Makefile in package genlisp                                                                
[rosmake-1] Starting >>> gennodejs [ make ]                                                                                                                    
[rosmake-3] Finished <<< gencpp ROS_NOBUILD in package gencpp
 No Makefile in package gencpp                                                                   
[rosmake-3] Starting >>> ros_environment [ make ]                                                                                                              
[rosmake-2] Finished <<< cpp_common ROS_NOBUILD in package cpp_common
 No Makefile in package cpp_common                                                       
[rosmake-0] Finished <<< geneus ROS_NOBUILD in package geneus
 No Makefile in package geneus                                                                   
[rosmake-2] Starting >>> rostime [ make ]                                                                                                                      
[rosmake-0] Starting >>> cmake_modules [ make ]                                                                                                                
[rosmake-1] Finished <<< gennodejs ROS_NOBUILD in package gennodejs
 No Makefile in package gennodejs                                                          
[rosmake-3] Finished <<< ros_environment ROS_NOBUILD in package ros_environment
 No Makefile in package ros_environment                                        
[rosmake-1] Starting >>> message_generation [ make ]                                                                                                           
[rosmake-0] Finished <<< cmake_modules ROS_NOBUILD in package cmake_modules
 No Makefile in package cmake_modules                                              
[rosmake-3] Starting >>> roslang [ make ]                                                                                                                      
[rosmake-0] Starting >>> rospack [ make ]                                                                                                                      
[rosmake-1] Finished <<< message_generation ROS_NOBUILD in package message_generation
 No Makefile in package message_generation                               
[rosmake-2] Finished <<< rostime ROS_NOBUILD in package rostime
 No Makefile in package rostime                                                                
[rosmake-2] Starting >>> roscpp_traits [ make ]                                                                                                                
[rosmake-1] Starting >>> xmlrpcpp [ make ]                                                                                                                     
[rosmake-3] Finished <<< roslang ROS_NOBUILD in package roslang
 No Makefile in package roslang                                                                
[rosmake-3] Starting >>> rosgraph [ make ]                                                                                                                     
[rosmake-1] Finished <<< xmlrpcpp ROS_NOBUILD in package xmlrpcpp
 No Makefile in package xmlrpcpp                                                             
[rosmake-0] Finished <<< rospack ROS_NOBUILD in package rospack
 No Makefile in package rospack                                                                
[rosmake-1] Starting >>> rosclean [ make ]                                                                                                                     
[rosmake-0] Starting >>> roslib [ make ]                                                                                                                       
[rosmake-3] Finished <<< rosgraph ROS_NOBUILD in package rosgraph
 No Makefile in package rosgraph                                                             
[rosmake-2] Finished <<< roscpp_traits ROS_NOBUILD in package roscpp_traits
 No Makefile in package roscpp_traits                                              
[rosmake-3] Starting >>> rosparam [ make ]                                                                                                                     
[rosmake-2] Starting >>> roscpp_serialization [ make ]                                                                                                         
[rosmake-3] Finished <<< rosparam ROS_NOBUILD in package rosparam
 No Makefile in package rosparam                                                             
[rosmake-3] Starting >>> rosmaster [ make ]                                                                                                                    
[rosmake-0] Finished <<< roslib ROS_NOBUILD in package roslib
 No Makefile in package roslib                                                                   
[rosmake-0] Starting >>> rosunit [ make ]                                                                                                                      
[rosmake-2] Finished <<< roscpp_serialization ROS_NOBUILD in package roscpp_serialization
 No Makefile in package roscpp_serialization                         
[rosmake-2] Starting >>> message_runtime [ make ]                                                                                                              
[rosmake-1] Finished <<< rosclean ROS_NOBUILD in package rosclean
 No Makefile in package rosclean                                                             
[rosmake-1] Starting >>> class_loader [ make ]                                                                                                                 
[rosmake-3] Finished <<< rosmaster ROS_NOBUILD in package rosmaster
 No Makefile in package rosmaster                                                          
[rosmake-2] Finished <<< message_runtime ROS_NOBUILD in package message_runtime
 No Makefile in package message_runtime                                        
[rosmake-0] Finished <<< rosunit ROS_NOBUILD in package rosunit
 No Makefile in package rosunit                                                                
[rosmake-2] Starting >>> std_msgs [ make ]                                                                                                                     
[rosmake-0] Starting >>> rosbuild [ make ]                                                                                                                     
[rosmake-1] Finished <<< class_loader ROS_NOBUILD in package class_loader
 No Makefile in package class_loader                                                 
[rosmake-1] Starting >>> std_srvs [ make ]                                                                                                                     
[rosmake-3] Starting >>> roslz4 [ make ]                                                                                                                       
[rosmake-1] Finished <<< std_srvs ROS_NOBUILD in package std_srvs
 No Makefile in package std_srvs                                                             
[rosmake-2] Finished <<< std_msgs ROS_NOBUILD in package std_msgs
 No Makefile in package std_msgs                                                             
[rosmake-0] Finished <<< rosbuild ROS_NOBUILD in package rosbuild
 No Makefile in package rosbuild                                                             
[rosmake-0] Starting >>> rosconsole [ make ]                                                                                                                   
[rosmake-2] Starting >>> geometry_msgs [ make ]                                                                                                                
[rosmake-1] Starting >>> rosgraph_msgs [ make ]                                                                                                                
[rosmake-3] Finished <<< roslz4 ROS_NOBUILD in package roslz4
 No Makefile in package roslz4                                                                   
[rosmake-1] Finished <<< rosgraph_msgs ROS_NOBUILD in package rosgraph_msgs
 No Makefile in package rosgraph_msgs                                              
[rosmake-2] Finished <<< geometry_msgs ROS_NOBUILD in package geometry_msgs
 No Makefile in package geometry_msgs                                              
[rosmake-0] Finished <<< rosconsole ROS_NOBUILD in package rosconsole
 No Makefile in package rosconsole                                                       
[rosmake-0] Starting >>> roscpp [ make ]                                                                                                                       
[rosmake-1] Starting >>> pluginlib [ make ]                                                                                                                    
[rosmake-0] Finished <<< roscpp ROS_NOBUILD in package roscpp
 No Makefile in package roscpp                                                                   
[rosmake-0] Starting >>> rosout [ make ]                                                                                                                       
[rosmake-3] Starting >>> rospy [ make ]                                                                                                                        
[rosmake-1] Finished <<< pluginlib ROS_NOBUILD in package pluginlib
 No Makefile in package pluginlib                                                          
[rosmake-0] Finished <<< rosout ROS_NOBUILD in package rosout
 No Makefile in package rosout                                                                   
[rosmake-0] Starting >>> roslaunch [ make ]                                                                                                                    
[rosmake-0] Finished <<< roslaunch ROS_NOBUILD in package roslaunch
 No Makefile in package roslaunch                                                          
[rosmake-3] Finished <<< rospy ROS_NOBUILD in package rospy
 No Makefile in package rospy                                                                      
[rosmake-3] Starting >>> rostest [ make ]                                                                                                                      
[rosmake-3] Finished <<< rostest ROS_NOBUILD in package rostest
 No Makefile in package rostest                                                                
[rosmake-3] Starting >>> topic_tools [ make ]                                                                                                                  
[rosmake-1] Starting >>> rosbag_storage [ make ]                                                                                                               
[rosmake-3] Finished <<< topic_tools ROS_NOBUILD in package topic_tools
 No Makefile in package topic_tools                                                    
[rosmake-1] Finished <<< rosbag_storage ROS_NOBUILD in package rosbag_storage
 No Makefile in package rosbag_storage                                           
[rosmake-1] Starting >>> rosbag [ make ]                                                                                                                       
[rosmake-1] Finished <<< rosbag ROS_NOBUILD in package rosbag
 No Makefile in package rosbag                                                                   
[rosmake-1] Starting >>> sensor_msgs [ make ]                                                                                                                  
[rosmake-2] Starting >>> rosmsg [ make ]                                                                                                                       
[rosmake-1] Finished <<< sensor_msgs ROS_NOBUILD in package sensor_msgs
 No Makefile in package sensor_msgs                                                    
[rosmake-1] Starting >>> cv_bridge [ make ]                                                                                                                    
[rosmake-2] Finished <<< rosmsg ROS_NOBUILD in package rosmsg
 No Makefile in package rosmsg                                                                   
[rosmake-2] Starting >>> rosservice [ make ]                                                                                                                   
[rosmake-1] Finished <<< cv_bridge ROS_NOBUILD in package cv_bridge
 No Makefile in package cv_bridge                                                          
[rosmake-2] Finished <<< rosservice ROS_NOBUILD in package rosservice
 No Makefile in package rosservice                                                       
[rosmake-2] Starting >>> dynamic_reconfigure [ make ]                                                                                                          
[rosmake-2] Finished <<< dynamic_reconfigure ROS_NOBUILD in package dynamic_reconfigure
 No Makefile in package dynamic_reconfigure                            
[rosmake-2] Starting >>> lsd_slam_viewer [ make ]                                                                                                              
[ rosmake ] Last 40 linesd_slam_viewer: 3.3 sec ]                                                                                   [ 1 Active 46/48 Complete ]
{-------------------------------------------------------------------------------
    CMakeLists.txt:21 (find_package)
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  -- Found unsuitable Qt version "5.9.5" from /usr/bin/qmake
  Qt QTOPENGL library not found.
  Qt QTGUI library not found.
  Qt QTXML library not found.
  Qt QTCORE library not found.
  -- Could NOT find QGLVIEWER (missing: QGLVIEWER_LIBRARY) 
  MSG: gencfg_cpp on:LSDSLAMViewerParams.cfg
  ERROR [gendeps] 1 Finding dependencies for /home/username/rosbuild_ws/package_dir/lsd_slam/lsd_slam_viewer/cfg/LSDSLAMViewerParams.cfg
  ***********************************************************************************
  load_module did not return. Unable to determine dependencies for file listed above.
  ***********************************************************************************
  Traceback (most recent call last):
    File "/opt/ros/melodic/share/dynamic_reconfigure/cmake/gendeps", line 66, in <module>
      imp.load_module("__main__", f, srcfile, ('.cfg', 'U', 1))
    File "/home/username/rosbuild_ws/package_dir/lsd_slam/lsd_slam_viewer/cfg/LSDSLAMViewerParams.cfg", line 20, in <module>
      gen.add("scaledDepthVarTH", double_t, 0, "log10 of threshold on point's variance, in the respective keyframe's scale. ", -3, -10, 1)
    File "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py", line 274, in add
      self.group.add(name, paramtype, level, description, default, min, max, edit_method)
    File "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py", line 145, in add
      check_description(description)
    File "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py", line 69, in check_description
      raise Exception(r"""quotes not allowed in description string `%s`""" % description)
  Exception: quotes not allowed in description string `log10 of threshold on point's variance, in the respective keyframe's scale. `
  
  CMake Error at /opt/ros/melodic/share/dynamic_reconfigure/cmake/cfgbuild.cmake:78 (string):
    string sub-command REPLACE requires at least four arguments.
  Call Stack (most recent call first):
    /opt/ros/melodic/share/dynamic_reconfigure/cmake/cfgbuild.cmake:99 (gencfg_cpp)
    CMakeLists.txt:29 (include)
  
  
  -- [rosbuild] Found SSE3 extensions, using flags: -msse3 -mfpmath=sse
  -- Configuring incomplete, errors occurred!
  See also "/home/username/rosbuild_ws/package_dir/lsd_slam/lsd_slam_viewer/build/CMakeFiles/CMakeOutput.log".
  See also "/home/username/rosbuild_ws/package_dir/lsd_slam/lsd_slam_viewer/build/CMakeFiles/CMakeError.log".
  /opt/ros/melodic/share/mk/cmake.mk:7: recipe for target 'all' failed
-------------------------------------------------------------------------------}
[ rosmake ] Output from build of package lsd_slam_viewer written to:
[ rosmake ]    /home/username/.ros/rosmake/rosmake_output-20190218-162754/lsd_slam_viewer/build_output.log
[rosmake-2] Finished <<< lsd_slam_viewer [FAIL] [ 3.43 seconds ]                                                                                               
[ rosmake ] Halting due to failure in package lsd_slam_viewer. 
[ rosmake ] Waiting for other threads to complete.                                             
[ rosmake ] Results:                                                                                                                                           
[ rosmake ] Built 47 packages with 1 failures.                                                                                                                 
[ rosmake ] Summary output to directory                                                                                                                        
[ rosmake ] /home/username/.ros/rosmake/rosmake_output-20190218-162754
```

How to fix it ?

I'm using ubuntu 18.04 64 bit with ros-melodic. 
Thanks

**Comment by toonnii** [comment]
Hello 
Do you fix it?

**Comment by aayushi363** [comment]
Facing same issue please help!!

**Comment by aachamehul021** [comment]
still looking for an answer

**Comment by Marc-3d** [comment]
Hi, I found the solution 🔍 

Edit the file `/lsd_slam/lsd_slam_viewer/cfg/LSDSLAMViewerParams.cfg` and remove all 

> 's

within strings variables. 
<br>

For example, in line 20 of `LSDSLAMViewerParams.cfg`, I changed "point's" to "point s", and "keyframe's" to "keyframe s": 

BEFORE: `gen.add("scaledDepthVarTH", double_t, 0, "log10 of threshold on point's variance, in the respective keyframe's scale. ", -3, -10, 1)`
AFTER: `gen.add("scaledDepthVarTH", double_t, 0, "log10 of threshold on point s variance, in the respective keyframe s scale. ", -3, -10, 1)`

In total, you have to remove `'s` from a handful of lines in `/lsd_slam/lsd_slam_viewer/cfg/LSDSLAMViewerParams.cfg`, and from a handful of lines in `/lsd_slam/lsd_slam_core/cfg/LSDDebugParams.cfg`.
